import torch
import json
from swift.llm import (
    get_model_tokenizer, get_template, inference,
    get_default_template_type
)
from swift.tuners import Swift
from swift.utils import seed_everything
from concurrent.futures import ThreadPoolExecutor, as_completed
import logging

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")

import re
import json

expert, tokenizer =  get_model_tokenizer("internvl2-2b", torch.bfloat16,
                        model_kwargs={'device_map': 'auto'}, model_id_or_path="../videoRM/Internvl/pretrain/InternVL2-2B")
expert = Swift.from_pretrained(
        expert, "../videoRM/finetune_result/alignment_expert_Internvl2_2B_base_model_lora_score/internvl2-2b/v0-20241030-081412/checkpoint-741", "alignmnet", inference_mode=True)

expert.generation_config.max_new_tokens = 1024

template_type = get_default_template_type("internvl2-2b")
template = get_template(template_type, tokenizer)
video_path_0 = ["../videos/hpdbv2_videos/HPDv2_train_image0_6021.mp4"]
video_path_1 = ["../videos/hpdbv2_videos/HPDv2_train_image1_6021.mp4"]

total_prompt = "You are a professional text-to-video alignment evaluator. Your task is to determine how well a video generated by a given prompt matches the prompt from the following five perspectives.\n\n1. Object: the human, animal, or any other object specified in the prompt;\n2. Attribute: the attribute (e.g., color/shape/size/texture) of an object specified in the prompt;\n3. Action: the object action specified in the prompt is not present in the video;\n4. Counting: the count of humans/animals/objects in the video should match that specified in the prompt;\n5. Location: the spatial or location relationship of the entities in the video should match that specified in the prompt.\n\nLet's evaluate text-video alignment now! Please rate the video directly on a scale between 0 and 100 in the following json format:\n\n{\"score\":0-100}.\n\nInput text prompt : \n\n\"The video features a stop-motion animation of a woman in a long, light blue and gold dress with green accents and patterns. The character has brown hair styled in an elegant updo and bluish eyes. She stands against a black background with occasional yellow patterns and small lights around her.\n\nThroughout the video, the camera angles remain consistent, focusing on capturing her full-body appearance and the intricate details of her dress. The stop-motion style is depicted by the slight shifts in her posture and arm positioning as she maintains a poised and graceful demeanor. The video does not include any other characters or movements, keeping the focus solely on the woman in the dress.\""

result, _ = inference(expert, template, total_prompt, videos=video_path_0)
print(result)

result, _ = inference(expert, template, total_prompt, videos=video_path_1)
print(result)